# SPDX-FileCopyrightText: 2023 Springtime authors
#
# SPDX-License-Identifier: Apache-2.0

site_name: Springtime documentation
repo_url: https://github.com/phenology/springtime
repo_name: Springtime

nav:
  - Home:
      - About: index.md
      - Getting started: setup.md
  - User Guide:
      - Getting started: setup.md
      - CRIB installation: crib.md
      - Example workflow: notebooks/pk_wishful_workflows.ipynb
      - Available recipes: recipes.md
  - Datasets:
      - Data sources and existing tools: datasets.md
      - Field observations:
        - National Phenology Network: notebooks/datasets_npn.ipynb
        - Plant Phenology Ontology: notebooks/datasets_ppo.ipynb
        - Pan European Phenology: notebooks/datasets_pep725.ipynb
      - Satellites:
        - MODIS: notebooks/datasets_modis.ipynb
      - Meteorology:
        - Daymet: notebooks/datasets_daymet.ipynb
        - E-Obs: notebooks/datasets_eobs.ipynb
  - Developer Guide: develop.md

theme:
  name: material
  custom_dir: docs/overrides
  logo: lilac_cc0.jpg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/beaker-16

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: deep purple
      accent: deep purple

plugins:
- mkdocs-jupyter:
    include_source: True
    include: [
      "pk_wishful_workflows.ipynb",
      "datasets_npn.ipynb",
      "datasets_ppo.ipynb",
      "datasets_pep725.ipynb",
      "datasets_modis.ipynb",
      "datasets_eobs.ipynb",
      "datasets_daymet.ipynb",
      ]
- include-markdown
- search
extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
