# SPDX-FileCopyrightText: 2023 Springtime authors
#
# SPDX-License-Identifier: Apache-2.0

site_name: Springtime documentation
repo_url: https://github.com/phenology/springtime
repo_name: Springtime

nav:
  - Home: index.md
  - Installation: setup.md
  # - Usage: usage.md
  - User guide:
    - Intro: notebooks/user_guide/intro.ipynb
    - Datasets:
      - datasets.md
      - PEP725: notebooks/user_guide/datasets/pep725.ipynb
      - EOBS: notebooks/user_guide/datasets/eobs.ipynb
    - Workflows: notebooks/user_guide/combining_data.ipynb
    - Modelling:
      - Pycaret & sklearn: placeholder.md
      - Pyphenology: placeholder.md
      - Mixed effects: placeholder.md
    - Example use cases:
      - Experiment 1: placeholder.md
      - Experiment 2: placeholder.md
      # - Example recipes: recipes.md
  # - Datasets:
  #     - Data sources and existing tools:
  #     - Field observations:
  #       - National Phenology Network: notebooks/datasets_npn.ipynb
  #       - Plant Phenology Ontology: notebooks/datasets_ppo.ipynb
  #       - Pan European Phenology: notebooks/datasets_pep725.ipynb
  #       - Phenocam: notebooks/datasets_phenocam.ipynb
  #     - Satellites:
  #       - MODIS: notebooks/datasets_modis.ipynb
  #       - AppEEARS: notebooks/datasets_modis_appeears.ipynb
  #     - Meteorology:
  #       - Daymet: notebooks/datasets_daymet.ipynb
  #       - E-OBS: notebooks/datasets_eobs.ipynb
  #     - Recipe Reference: clireference/datasets/
  - Developer Guide: develop.md
  - API Reference: reference/springtime/datasets/
  # - Models: models.md

theme:
  name: material
  custom_dir: docs/overrides
  logo: lilac_cc0.jpg
  features:
    - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/beaker-16

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: deep purple
      accent: deep purple

plugins:
- mkdocs-jupyter:
    include_source: True
    # TODO no need to specify each file.
    include: [
      "intro.ipynb",
      "pep725.ipynb",
      "eobs.ipynb",
      "combining_data.ipynb",
      # "pk_wishful_workflows.ipynb",
      # "datasets_npn.ipynb",
      # "datasets_ppo.ipynb",
      # "datasets_modis.ipynb",
      # "datasets_daymet.ipynb",
      # "datasets_phenocam.ipynb",
      # "datasets_modis_appeears.ipynb",
      ]
- include-markdown
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          members_order: source
          show_source: false
          show_signature: true
          inherited_members: true  # https://github.com/mkdocstrings/python/issues/40
          show_if_no_docstring: false
          signature_crossrefs: true
          docstring_section_style: table
          show_submodules: false
          show_root_heading: false
          show_root_toc_entry: false
          show_root_full_path: false
          show_object_full_path: false
          show_symbol_type_heading: true  # currently only available for insiders
        import:
          - https://docs.python.org/3/objects.inv
          # We are still on Pydantic v1 which does not have intersphinx
          # See https://github.com/phenology/springtime/issues/156
          # Need to update to v2 to be able to use intersphinx link below
          # - https://docs.pydantic.dev/latest/objects.inv
          - https://geopandas.org/en/stable/objects.inv
          - https://pandas.pydata.org/pandas-docs/stable/objects.inv
          - https://docs.xarray.dev/en/stable/objects.inv
- gen-files:  # Auto-generate API reference files
    scripts:
        - docs/gen_apiref_datasets.py
        # - docs/gen_cliref_datasets.py
- literate-nav:  # Create an index for the auto-generated api reference
    nav_file: SUMMARY.md
- section-index
extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

watch:
- src

extra_css:
  - "api.css"
