[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "springtime"
description = "Spatiotemporal phenology research with interpretable models"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "Apache 2.0" }
keywords = [
  "phenology",
]
authors = [
  { name = "Peter Kalverla", email = "peter.kalverla@gmx.com" },
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Intended Audience :: Science/Research",
]
dependencies = [
  "xarray",
  "pyphenology",
  "scipy",  # unspecified dependency of pyphenology
  "joblib",  # unspecified dependency of pyphenology
  "pyyaml",
  "pandas",
  "pydantic",
  "click",
  "rpy2",
  "geopandas",
  "dask",  # needed for xarray.open_mfdataset()
]
dynamic = ["version", "optional-dependencies"]

[project.urls]
Documentation = "https://github.com/phenology/springtime#readme"
Issues = "https://github.com/phenology/springtime/issues"
Source = "https://github.com/phenology/springtime"

[project.scripts]
springtime = "springtime.main:cli"

[tool.hatch.version]
path = "src/springtime/__init__.py"

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
docs = ["docs/requirements.txt"]

[tool.hatch.envs.dev]
detached = true
dependencies = [
  "black",
  "mypy",
  "pytest",
  "ruff",
]

[tool.hatch.envs.default]
features = ["docs"]
template = "dev"

[tool.hatch.envs.default.scripts]
quality-checks = [
  "black src tests",
  "ruff check src tests --fix",
  "mypy src tests",
  "pytest",
]

[tool.mypy]
ignore_missing_imports = true
