[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "py_ppo"
description = "Download data from the plant phenology portal"
version = "0.0.1"
readme = "README.md"
license = { text = "Apache 2.0" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Intended Audience :: Science/Research",
]
keywords = [
  "phenology",
]
requires-python = ">=3.8"
dependencies = [
    "requests",
    "pandas",
]
