[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "springtime"
description = "Project-specific code snippets for the springtime project"
version = "0.0.1"
readme = "README.md"
license = { text = "Apache 2.0" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Intended Audience :: Science/Research",
]
keywords = [
  "phenology",
]
requires-python = ">=3.8"
dependencies = [
  "scikit-learn",
  "numpy",
  "pyphenology",
]
