# SPDX-FileCopyrightText: 2023 Springtime authors
#
# SPDX-License-Identifier: Apache-2.0

name: Lint files and run tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash -el {0}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
    - name: pytest
      run: hatch run pytest
    - name: ruff
      run: hatch run ruff check src
    - name: mypy
      if: success() || failure()
      run: hatch run mypy src tests
    - name: reuse
      if: success() || failure()
      run: hatch run reuse lint

