# SPDX-FileCopyrightText: 2023 Springtime authors
#
# SPDX-License-Identifier: Apache-2.0

name: Lint files and type checking

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    shell: bash -el {0}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment from environment.yml
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.4.6'  # 1.4.7 has a bug
        cache-environment: true
        environment-file: environment.yml
    - name: Install R dependencies
      run: |
        Rscript -e 'devtools::install_github("bluegreen-labs/phenor", upgrade="never")'
        Rscript -e 'devtools::install_github("ropensci/rppo", upgrade="never")'
        Rscript -e 'install.packages(c("daymetr", "MODISTools", "phenocamr", "rnpn"), repos = "http://cran.us.r-project.org")'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
    - name: Run checks
      run: |
        hatch run ruff check src
        hatch run mypy src tests
        hatch run reuse lint
        hatch run pytest
