name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install conda environment with R and python in it
      run: |
        conda env update --file environment.yml --name base

    - name: Install additional R dependencies
      run: |
        Rscript -e 'devtools::install_github("bluegreen-labs/phenor")'
        Rscript -e 'devtools::install_github("ropensci/rppo")'
        Rscript -e 'install.packages("daymetr")'

    - name: Verify installation is correct
      run: |
        hatch run python -m r2py.situation

    - name: Test with pytest
      run: |
        hatch run pytest
