name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'

    - name: Install R dependencies
      run: |
        Rscript -e '.libPaths()'
        Rscript -e 'devtools::install_github("bluegreen-labs/phenor")'
        Rscript -e 'devtools::install_github("ropensci/rppo")'
        Rscript -e 'install.packages("devtools")'
        Rscript -e 'install.packages("daymetr")'

    - name: Verify installation
      run: |
        hatch run python -m r2py.situation

    - name: Run tests
      run: |
        hatch run pytest
